# Generated by Django 2.2.1 on 2019-05-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiasModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumen', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('cupos', models.IntegerField()),
                ('Familia', models.CharField(choices=[('N', 'Noticia'), ('E', 'Evento')], default='N', max_length=1)),
            ],
        ),
    ]
