# Generated by Django 2.2.1 on 2019-05-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoticiasCrud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiasmodelo',
            name='cupos',
        ),
    ]
