# Generated by Django 2.2.1 on 2019-05-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticiasCrud', '0003_remove_noticiasmodelo_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiasmodelo',
            name='Familia',
            field=models.CharField(choices=[('N', 'Noticia'), ('E', 'Evento')], default='N', max_length=1),
        ),
    ]
