# Generated by Django 2.2.1 on 2019-05-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticiasCrud', '0004_noticiasmodelo_familia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiasmodelo',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
    ]
