# Generated by Django 2.2.1 on 2019-05-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticiasCrud', '0005_auto_20190502_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiasmodelo',
            name='detalle',
            field=models.CharField(default='nada', max_length=800),
            preserve_default=False,
        ),
    ]
